app = "markal"
primary_region = "mia"

[build]
  dockerfile = "Dockerfile"

# Split architecture into two separate processes/machines
[processes]
  web = "node server.mjs"
  signaling = "node server/signaling/index.js"

# Public service for the Web Application
[[services]]
  processes = ["web"]
  internal_port = 8080
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true
    
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

# Public service for the WebRTC Signaling Server
[[services]]
  processes = ["signaling"]
  internal_port = 4444
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 4444
